# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('typeOfProduct', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institutionslug', models.SlugField(allow_unicode=True)),
                ('title', models.CharField(max_length=512)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Description', models.TextField()),
                ('productImage1', models.ImageField(upload_to='photos/')),
                ('productImage2', models.ImageField(blank=True, upload_to='photos/')),
                ('productImage3', models.ImageField(blank=True, upload_to='photos/')),
                ('productImage4', models.ImageField(blank=True, upload_to='photos/')),
                ('soldFlag', models.BooleanField(default=False)),
                ('createdTime', models.DateTimeField(auto_now=True)),
                ('Institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='basic_app.IntitutionModel')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='productapp.ProductCategoryModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdTime'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='productsmodel',
            unique_together=set([('user', 'categoryid', 'title')]),
        ),
    ]
