# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='Institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='basic_app.IntitutionModel'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='productImage1',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
