# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='Institution',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='basic_app.IntitutionModel'),
            preserve_default=False,
        ),
    ]
