# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 09:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_productsmodel_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='sellerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
