# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_auto_20171107_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='Institutionslug',
            field=models.SlugField(allow_unicode=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
