# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_auto_20171029_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='Institution',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='basic_app.IntitutionModel'),
        ),
    ]
