# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 02:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productapp', '0004_auto_20171029_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsmodel',
            old_name='sellerid',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='productsmodel',
            unique_together=set([('user', 'categoryid', 'title')]),
        ),
    ]
