# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntitutionModel',
            fields=[
                ('name', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugInst', models.SlugField(allow_unicode=True)),
                ('NameOfInstitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.IntitutionModel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
