# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20171103_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intitutionmodel',
            options={'ordering': ['name']},
        ),
    ]
