# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20171105_1542'),
        ('basic_app', '0003_auto_20171103_0829'),
    ]

    operations = [
    ]
