# Generated by Django 2.0.3 on 2018-04-08 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_private_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='opponent',
            field=models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='Dialog opponent'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='owner',
            field=models.ForeignKey(on_delete=True, related_name='selfDialogs', to=settings.AUTH_USER_MODEL, verbose_name='Dialog owner'),
        ),
        migrations.AlterField(
            model_name='message',
            name='dialog',
            field=models.ForeignKey(on_delete=True, related_name='messages', to='django_private_chat.Dialog', verbose_name='Dialog'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=True, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
